[build]
  command = "npm run build:netlify" # Skip CI environment variable to bypass type errors
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0" # Use the Node version compatible with your Next.js version
  NETLIFY_NEXT_PLUGIN_SKIP_TYPECHECK = "true" # Skip TypeScript checking

[[plugins]]
  package = "@netlify/plugin-nextjs"